name: CI

on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.8'
          - '1.9'
          - 'nightly'
        os:
          - ubuntu-latest
        arch:
          - x64

    steps:
      - uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      - name: Cache Julia dependencies
        uses: julia-actions/cache@v1
        with:
          path: ~/.julia
          key: julia-deps-${{ hashFiles('**/*.toml') }}

      - name: Install Julia dependencies
        run: julia -e 'import Pkg; Pkg.instantiate()'

      - name: Build Julia package
        uses: julia-actions/julia-buildpkg@v1

      - name: Run Julia tests
        uses: julia-actions/julia-runtest@v1
        with:
          project: .

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install Python dependencies
        run: |
          python -m pip install -r requirements/pycall.txt

      - name: Install PyCall dependencies
        run: julia -e 'import Pkg; Pkg.add("PyCall"); Pkg.build("PyCall")'
  
      - name: Run PyCall tests
        run: julia --project=tests test/runpytests.jl

      - name: Generate and upload code coverage
        uses: julia-actions/julia-processcoverage@v1

      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: lcov.info
